### ISSUE TITLE
Plans on release 0.4.1 (off branch 0.4.x, not master)

### ISSUE THREAD

**Issue by hartwork** [Libvisual/libvisual#108]
Hi!

libvisual [almost got removed from Gentoo](https://bugs.gentoo.org/840514#c9).  In that context, I had a closer look at the libvisual distro packaging situation. What I found:
- Many distros [have libvisual 0.4.0 packaged](https://repology.org/project/libvisual/versions).
- Their packaging has 5+ local patches on top of 0.4.0, some crucial to even compile, with some overlap across distributions, e.g.:
  - Debian — https://sources.debian.org/patches/libvisual/0.4.0-18/
  - Fedora — https://src.fedoraproject.org/rpms/libvisual/tree/rawhide
  - Gentoo — https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files
- Compilers are changing and becoming more and more demanding over time.
- The lack of a follow-up release to 0.4 shows more over time.

So while libvisual 0.5.0 may not be ready for release on `master`, I believe preparing a release 0.4.1 based of 0.4.0 plus essential distro patches would help both libvisual and distributions and their relation.

I have therefore pushed a new branch `0.4.x` now with the minimal set of patches to get 0.4.x to compile:
- 806633a8 Drop files auto-generated by GNU Autotools
- 45f773c2 Drop file `lvconfig.h` that is generated by `./configure`
- afd29635 `libvisual/configure.ac`: Fix `--enable-threads`
- c5ae7bb0 `libvisual/lv_cpu.c`: Remove `X86_FXSR_MAGIC` guard (not defined anywhere)
- 31f5e5f5 `libvisual/lv_defines.h`: Fix redefine
- 1bf6d28e `libvisual/configure.ac`: Bump gettext version due to `@MKINSTALLDIRS@` issues
- b4d58f6e actions: Add Linux CI inspired by master branch

What's needed more (e.g. for Clang 16+) is:
- A fix for implicit function declarations — #106
- Some fix for a violation to strict aliasing — #107
- Analyzing and deciding on the remaining distro patches, more on that soon.
  For now let me just say: the improved AltiVec detection needs a closer look and potentially license check, and the Debian translation and spelling changes are probably serving `master` better  than `0.4.x`.
  
Please feel invited for review, review is appreciated.

Best, Sebastian

**Comment by hartwork** [comment]
Here's a map of on the current state of analysis and integration of downstream patches that I'll try to keep in sync with reality over time. If you'd like to join in on this, let's maybe hop on a quick call to save both of us some typing and ping-pong…

- [ ] Debian
  - [ ] [libvisual](https://sources.debian.org/patches/libvisual/0.4.0-18/)
    - [ ] [`10_fix_x86_fxsr_magic.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/10_fix_x86_fxsr_magic.patch/) — c5ae7bb077781d0ff0194d89def3923c2bbf9175 on branch `0.4.x`, AltiVec part TODO
    - [x] [`20_redefine_fix.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/20_redefine_fix.patch/) — 31f5e5f57b60551dcb2fdc7b466f2ee043d84eba
    - [x] [`30_configure_fix.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/30_configure_fix.patch/) — covered by 1bf6d28ee2a1d62e7b60bd3e3ea0027245dcd7a3 on branch `0.4.x`
    - [ ] [`40_fix_format-security-error.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/40_fix_format-security-error.patch/) — no actual security impact, warning silencer, TODO
    - [ ] [`50_fix-spelling-errors.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/50_fix-spelling-errors.patch/) — TODO
    - [ ] [`60_add_german_translation.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/60_add_german_translation.patch/) — TODO
    - [ ] [`70_fix_some_GCC_warnings.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/70_fix_some_GCC_warnings.patch/) — TODO
    - [ ] [`80_fix_spelling.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/80_fix_spelling.patch/) — TODO
    - [ ] [`90_update-DE-translation.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/90_update-DE-translation.patch/) — TODO
    - [ ] [`95_fix-FTCBFS.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/95_fix-FTCBFS.patch/) — TODO
  - [ ] [libvisual-plugins](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0+dfsg1-10/)
    - [x] [`10_disable-gforce-dfsg.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/10_disable-gforce-dfsg.patch/) — not upstreamable
    - [ ] [`20_64-bit_JESS_fix.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/20_64-bit_JESS_fix.patch/) — needs manual testing, TODO
    - [ ] [`30_build_against_gl_fixes.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/30_build_against_gl_fixes.patch/) — pull request #112
    - [x] [`40_lv_analyzer_build_fix.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/40_lv_analyzer_build_fix.patch/) — pull request #111
    - [ ] [`50_fix_po.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/50_fix_po.patch/) — needed? TODO
    - [ ] [`60_alsa_m4_macro.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/60_alsa_m4_macro.patch/) — needed? TODO
    - [ ] [`70_no-const-vispluginfo-in-nastyfft.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/70_no-const-vispluginfo-in-nastyfft.patch/) — needs manual testing, TODO
    - [ ] [`80_fix_FTBFS_clang.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/80_fix_FTBFS_clang.patch/) — included in pull request #116
    - [ ] [`90_fix_some_gcc_warnings.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/90_fix_some_gcc_warnings.patch/) — TODO
    - [ ] [`95_fix_spelling.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/95_fix_spelling.patch/) — pull requests #114 and #115
- [ ] Fedora
  - [ ] [libvisual](https://src.fedoraproject.org/rpms/libvisual/tree/rawhide)
    - [ ] [`libvisual-0.4.0-better-altivec-detection.patch`](https://src.fedoraproject.org/rpms/libvisual/blob/rawhide/f/libvisual-0.4.0-better-altivec-detection.patch) — source? licensing? need? TODO
    - [x] [`libvisual-0.4.0-format-security.patch`](https://src.fedoraproject.org/rpms/libvisual/blob/rawhide/f/libvisual-0.4.0-format-security.patch) — same as [`40_fix_format-security-error.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/40_fix_format-security-error.patch/) in Debian
    - [x] [`libvisual-0.4.0-inlinedefineconflict.patch`](https://src.fedoraproject.org/rpms/libvisual/blob/rawhide/f/libvisual-0.4.0-inlinedefineconflict.patch) — alternative approach in commit 31f5e5f57b60551dcb2fdc7b466f2ee043d84eba on `0.4.x`
    - [ ] [`libvisual-0.4.0-respect-environment-ldflags.patch`](https://src.fedoraproject.org/rpms/libvisual/blob/rawhide/f/libvisual-0.4.0-respect-environment-ldflags.patch) — TODO
  - [x] [libvisual-plugins](https://src.fedoraproject.org/rpms/libvisual-plugins/c/3df0e755879c6c9db552de2f59fb56033f7b23ec?branch=rawhide)
- [ ] Gentoo
  - [ ] [libvisual](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files)
    - [ ] [`libvisual-0.4.0-better-altivec-detection.patch`](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-better-altivec-detection.patch) — source? licensing? need? TODO
    - [x] [`libvisual-0.4.0-cond.patch`](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-cond.patch) — commit afd29635ee34e2274bc5fb9df6208e2d8ccadbe5 on `0.4.x`
    - [x] [`libvisual-0.4.0-conditions.patch`](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-conditions.patch) — covered by commit c5ae7bb077781d0ff0194d89def3923c2bbf9175 on `0.4.x`
    - [ ] [`libvisual-0.4.0-detect_amd64.patch`](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-detect_amd64.patch) — TODO
    - [x] [`libvisual-0.4.0-format-security.patch`](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-format-security.patch) — same as [`40_fix_format-security-error.patch`](https://sources.debian.org/patches/libvisual/0.4.0-18/40_fix_format-security-error.patch/) in Debian
    - [x] [`libvisual-0.4.0-inlinedefineconflict.patch`](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-inlinedefineconflict.patch) — alternative approach in commit 31f5e5f57b60551dcb2fdc7b466f2ee043d84eba on `0.4.x`
  - [ ] [libvisual-plugins](http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/23/libvisual-plugins-0.4.0-patches-4.tar.bz2)
    - [ ] `005_all_cxxflags.patch` — TODO
    - [ ] `010_all_LIBADD.patch` — pull request #112
    - [ ] `020_all_64bit.patch` — TODO
    - [x] `030_all_analyser.patch` — alternative commit 76ba0693903a51acdba3eb4106f09151008c9a5f on `0.4.x`
    - [ ] `040_all_gforce.patch` — TODO
    - [ ] `050_all_automagic.patch` — TODO
    - [ ] `060_all_gstreamer.patch` — TODO
    - [ ] `070_all_gforce-fbsd.patch` — TODO
    - [ ] `080_all_qa.patch` — TODO
    - [x] `090_all_nastyfft.patch` — same as [`70_no-const-vispluginfo-in-nastyfft.patch`](https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/70_no-const-vispluginfo-in-nastyfft.patch/) in Debian

**Comment by stuaxo** [comment]
Really good seeing all these go in, having an 0.4.1 + removing the need for all these per-distro patches is great work.

**Comment by hartwork** [comment]
@stuaxo glad to hear! :pray:

**Comment by stuaxo** [comment]
It's this sort of stuff that keeps a project alive - otherwise, at some point all those patches become too much work for all the distros to keep applying.

If real life wasn't intervening, I'd dive into this as well - but just happy to see it for now :)

**Comment by hartwork** [comment]
Quick update:
- I have reviewed all downstream patches by now, details further up at https://github.com/Libvisual/libvisual/issues/108#issuecomment-1328277087
- There are three open pull requests against 0.4.x that are likely to go into 0.4.1 as well — review welcome!
- I will create GitHub releases `libvisual-0.4.0` and `libvisual-plugins-0.4.0` at https://github.com/Libvisual/libvisual/releases adding past 0.4.0 source tarballs off SourceForge, in a few minutes. So that's not the new release yet, it's old 0.4.0.
- Release 0.4.1 is planned for "in a few days".

**Comment by hartwork** [comment]
0.4.1 has been [released just now](https://github.com/Libvisual/libvisual/releases), closing as fixed.
