### ISSUE TITLE
LV: Replace SIMD assembly routines with intrinsics or ORC

### ISSUE THREAD

**Issue by kaixiong** [Libvisual/libvisual#15]
## Task list
- [X] `visual_mem_copy` (Use libc)
- [X] `visual_mem_set` (Use libc)
- [ ] Bilinear scaling of 32-bit videos (Intrinsics)
- [X] Alpha Blending of 32-bit videos (Intrinsics)
- [X] SIMD math routines (ORC)
- [ ] SIMD `visual_mem_set16`, `visual_mem_set32`
